name: debdown_plus
description: Video/Audio Downloader powered by yt-dlp + ffmpeg
version: 6.6.6+1337

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  share_plus: ^9.0.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  flutter_downloader: ^1.11.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira-Variable.ttf