name: debdown_plus
description: "DebDown+ - Ultimate Auto-Scraping Video Downloader with Glitch Hacker Theme"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.2.4
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  receive_sharing_intent: ^1.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
    - assets/qr_dana.png
